// GENERATED by scripts/generate-bb2025-prayer-enhancements.mjs from the local fumbbl40k-server
// upstream/master tree; do not edit by hand.
//
// Java authorities:
//   ffb-common/.../inducement/bb2025/Prayer.java            — prayer table + enhancements()/eventMessage()
//   ffb-common/.../model/skill/Skill.java:65-91,317-319     — super(name, category[, defaultSkillValue])
//   ffb-common/.../mechanics/mixed/StatsMechanic.java:44-59 — BB2025 (@RulesCollection BB2020+BB2025) stat limits
//   ffb-common/.../Constant.java:31-35                      — Wisdom of the White Dwarf grantable SkillWithValues

export interface PrayerSkillGrant {
  /** Skill.getName() — the wire name a temporarySkillsMap entry carries. */
  readonly name: string;
  /** SkillClassWithValue value, or null when the prayer grants the skill without one. */
  readonly value: string | null;
}

export interface PrayerStatModifier {
  /** PlayerStatKey. */
  readonly stat: string;
  /** Canonical Java class name — TemporaryStatModifier.getName() is `${stat}-${modifierClass}`. */
  readonly modifierClass: string;
}

export interface PrayerEnhancementMeta {
  readonly name: string;
  readonly description: string;
  readonly duration: string;
  readonly affectsBothTeams: boolean;
  readonly changingPlayer: boolean;
  readonly eventMessage: string | null;
  readonly skills: readonly PrayerSkillGrant[];
  readonly modifiers: readonly PrayerStatModifier[];
}

/** Keyed by the Java enum constant name — exactly the string FIELD_MODEL_ADD_PRAYER/REMOVE_PRAYER carry
 *  (FieldModel.java:413,468 send `prayer.name()`, ModelChangeProcessor.java:170-172,217-219 resolve it). */
export const BB2025_PRAYERS: Record<string, PrayerEnhancementMeta> = {
  "TREACHEROUS_TRAPDOOR": {
    name: "Treacherous Trapdoor",
    description: "Trapdoors appear. On a roll of 1 a player stepping on them falls through them",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: true,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "FRIENDS_WITH_THE_REF": {
    name: "Friends with the Ref",
    description: "Argue the call succeeds on 5+",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "STILETTO": {
    name: "Stiletto",
    description: "One random player available to play this game gains Stab",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: " gains Stab",
    skills: [{ name: "Stab", value: null }],
    modifiers: [],
  },
  "IRON_MAN": {
    name: "Iron Man",
    description: "One chosen player available to play this game improves AV by 1 (Max 11+)",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: " gains 1 AV",
    skills: [],
    modifiers: [{ stat: "AV", modifierClass: "com.fumbbl.ffb.modifiers.TemporaryStatIncrementer" }],
  },
  "KNUCKLE_DUSTERS": {
    name: "Knuckle Dusters",
    description: "One chosen player available to play this game gains Mighty Blow",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: " gains Mighty Blow (+1)",
    skills: [{ name: "Mighty Blow", value: null }],
    modifiers: [],
  },
  "BAD_HABITS": {
    name: "Bad Habits",
    description: "D3 random opponent players available to play this game without Loner gain Loner (2+)",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: " gains Loner (2+)",
    skills: [{ name: "Loner", value: "2" }],
    modifiers: [],
  },
  "GREASY_CLEATS": {
    name: "Greasy Cleats",
    description: "One random opponent player available to play this game has his MA reduced by 1",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: " loses 1 MA",
    skills: [],
    modifiers: [{ stat: "MA", modifierClass: "com.fumbbl.ffb.modifiers.TemporaryStatDecrementer" }],
  },
  "BLESSING_OF_NUFFLE": {
    name: "Blessing of Nuffle",
    description: "One random player available to play this game gains Pro",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: " gains Pro",
    skills: [{ name: "Pro", value: null }],
    modifiers: [],
  },
  "MOLES_UNDER_THE_PITCH": {
    name: "Moles under the Pitch",
    description: "Rushes from opposing players have a -1 modifier",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "PERFECT_PASSING": {
    name: "Perfect Passing",
    description: "Completions generate 2 instead of 1 spp",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "DAZZLING_CATCHING": {
    name: "Dazzling Catching",
    description: "Caught passes generate 1 spp (from both teams, does not have to be accurate)",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "FAN_INTERACTION": {
    name: "Fan Interaction",
    description: "Casualties caused by crowd pushes generate 2 spp",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "FOULING_FRENZY": {
    name: "Fouling Frenzy",
    description: "Casualties caused by fouls generate 2 spp",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "THROW_A_ROCK": {
    name: "Throw a Rock",
    description: "Once a game at the start of any turn, a randomly selected opponent on the pitch gets knocked down on a 4+",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "UNDER_SCRUTINY": {
    name: "Under Scrutiny",
    description: "Fouls by opposing players are always spotted if armour is broken",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: false,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
  "INTENSIVE_TRAINING": {
    name: "Intensive Training",
    description: "One random player available to play this game gains a chosen Primary skill",
    duration: "UNTIL_END_OF_GAME",
    affectsBothTeams: false,
    changingPlayer: true,
    eventMessage: null,
    skills: [],
    modifiers: [],
  },
};

/** Skill.getDefaultSkillValue() for every COMMON/BB2025 skill — FieldModel.addIntensiveTrainingSkill
 *  (FieldModel.java:451-457) encodes the granted skill as `Name_${defaultSkillValue}`, INCLUDING `_0`. */
export const BB2025_SKILL_DEFAULT_VALUES: Record<string, number> = {
  "\"Excuse Me, Are You a Zoat?\"": 0,
  "+MA": 0,
  "+PA": 0,
  "Accurate": 0,
  "Always Hungry": 0,
  "Animal Savagery": 0,
  "Animosity": 0,
  "Ball and Chain": 0,
  "Big Hand": 0,
  "Block": 0,
  "Bloodlust": 2,
  "Bombardier": 0,
  "Bone Head": 0,
  "Break Tackle": 0,
  "Bullseye": 0,
  "Cannoneer": 0,
  "Catch": 0,
  "Chainsaw": 0,
  "Claws": 0,
  "Cloud Burster": 0,
  "Crushing Blow": 0,
  "Dauntless": 0,
  "Decay": 0,
  "Dirty Player": 0,
  "Disturbing Presence": 0,
  "Diving Catch": 0,
  "Diving Tackle": 0,
  "Dodge": 0,
  "Dump-Off": 0,
  "Dwarfen Grit": 0,
  "Dwarven Scourge": 0,
  "Extra Arms": 0,
  "Eye Gouge": 0,
  "Fend": 0,
  "Foul Appearance": 0,
  "Frenzied Rush": 0,
  "Frenzy": 0,
  "Grab": 0,
  "Guard": 0,
  "Hail Mary Pass": 0,
  "Halfling Luck": 0,
  "Horns": 0,
  "Hypnotic Gaze": 0,
  "I'll Carry You": 0,
  "Incorporeal": 0,
  "Indomitable": 0,
  "Juggernaut": 0,
  "Jump Up": 0,
  "Kick": 0,
  "Kick Team-Mate": 0,
  "Krump and Smash": 0,
  "Leader": 0,
  "Leap": 0,
  "Lethal Flight": 0,
  "Loner": 4,
  "Lord of Chaos": 0,
  "Master Assassin": 0,
  "Mesmerising Dance": 0,
  "Mighty Blow": 1,
  "Monstrous Mouth": 0,
  "Multiple Block": 0,
  "My Ball": 0,
  "Nerves of Steel": 0,
  "No Ball": 0,
  "Old Pro": 0,
  "On The Ball": 0,
  "Pass": 0,
  "Plague Ridden": 0,
  "Prehensile Tail": 0,
  "Pro": 0,
  "Punt": 0,
  "Ram": 0,
  "Really Stupid": 0,
  "Regeneration": 0,
  "Reliable": 0,
  "Right Stuff": 0,
  "Safe Pass": 0,
  "Savage Mauling": 0,
  "Secret Weapon": 0,
  "Shadowing": 0,
  "Shot to Nothing": 0,
  "Sidestep": 0,
  "Slashing Nails": 0,
  "Slayer": 0,
  "Sneaky Git": 0,
  "Sprint": 0,
  "Stab": 0,
  "Stand Firm": 0,
  "Strip Ball": 0,
  "Strong Arm": 0,
  "Stunty": 0,
  "Sure Feet": 0,
  "Sure Hands": 0,
  "Swoop": 0,
  "Tackle": 0,
  "Take Root": 0,
  "Taunt": 0,
  "Tentacles": 0,
  "The Ballista": 0,
  "Thick Skull": 0,
  "Throw Team-Mate": 0,
  "Timmm-ber!": 0,
  "Titchy": 0,
  "Trickster": 0,
  "Two Heads": 0,
  "Unchannelled Fury": 0,
  "Unsteady": 0,
  "Very Long Legs": 0,
  "Violent Innovator": 0,
  "Watch Out!": 0,
  "Wisdom of the White Dwarf": 0,
  "Woodland Fury": 0,
  "Working in Tandem": 0,
  "Wrestle": 0,
};

/** PlayerStatLimit per stat. Player.getStatWithModifiers (Player.java:245-262) applies a limit ONLY when at
 *  least one temporary modifier targets that stat, and treats 0 as "no bound". */
export const BB2025_STAT_LIMITS: Record<string, { min: number; max: number }> = {
  "MA": { min: 1, max: 9 },
  "ST": { min: 1, max: 8 },
  "AG": { min: 1, max: 6 },
  "PA": { min: 1, max: 6 },
  "AV": { min: 3, max: 11 },
};

/** The SkillWithValue set FIELD_MODEL_ADD_WISDOM resolves against (ModelChangeProcessor.java:187-190). */
export const WISDOM_GRANTABLE_SKILLS: readonly PrayerSkillGrant[] = [
  { name: "Break Tackle", value: null },
  { name: "Dauntless", value: null },
  { name: "Mighty Blow", value: "1" },
  { name: "Sure Feet", value: null },
];

/** Skill.enhancementSourceName() override in skill/bb2025/special/WisdomOfTheWhiteDwarf.java:28-30 — the
 *  temporarySkillsMap key FieldModel.addWisdomSkill (FieldModel.java:459-464) writes under. */
export const WISDOM_ENHANCEMENT_SOURCE = 'Granted by Wisdom of the White Dwarf';

/** PrayerFactory.intensivePrayer().getName() (factory/bb2025/PrayerFactory.java:24-27) — the
 *  temporarySkillsMap key FieldModel.addIntensiveTrainingSkill writes under. */
export const INTENSIVE_TRAINING_SOURCE = "Intensive Training";
